//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlService
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public string ReplyID { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string ReplyCollectionID { get; set; }
    
        public virtual replyCollection replyCollection { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
